### ISSUE TITLE
setting thermostat temperature not working

### ISSUE THREAD

**Issue by darkrain-nl** [JohnvandeVrugt/toonapilib4domoticz#1]
Setting the thermostat temperature is not working.
Looking at the code this perhaps is because the API is never asked to do this...

I tried fixing this but could not get it to work.

Perhaps being able to set the states (which I know is a todo/wish) makes this a non issue...

**Comment by JohnvandeVrugt** [comment]
States seem to have the same issue.
I guess we need to ask the toonapilib developer for same help on this matter.

**Comment by JohnvandeVrugt** [comment]
Open an [issue ](https://github.com/costastf/toonapilib/issues/23) at the toonapilib repository.

**Comment by scheric** [comment]
I am not an expert but maby this would work.
https://github.com/JohnvandeVrugt/toonapilib4domoticz/blob/7499981fa93e3237b6e31a0df3f2f2816a3a8fbb/plugin.py#L142

`szTemp = str(MyToon.thermostat_state.temperature)`
***

https://github.com/JohnvandeVrugt/toonapilib4domoticz/blob/7499981fa93e3237b6e31a0df3f2f2816a3a8fbb/plugin.py#L150

`MyToon.thermostat = szSetpoint`

**Comment by darkrain-nl** [comment]
Line 142 and 150 are for updating the devices inside Domoticz, that works fine.

This issue is about changing the real Toon thermostat setpoint via the API, Line 82, this is not working at the moment. @JohnvandeVrugt is in touch with the developer of the toonapilib for assistance on this matter.

**Comment by JohnvandeVrugt** [comment]
That's right, the developer of toonapilib already replied, but he needs some time to figure it out.

**Comment by costastf** [comment]
As far as I can see https://github.com/JohnvandeVrugt/toonapilib4domoticz/blob/5cfe4d2d6270b3933d2373be8a14823c209642ab/plugin.py#L82 should provide you with the usability that you need, setting the temperature to the provided value. Can you maybe provide some logging that would help troubleshoot the issue? I am not super excited by the usage of globals and not sure if that is the preferred way to work in domoticz. What would help is if I can get a log output of the setting of the value. Please enable debug logging and provide the output here and see where that takes us or maybe guide me with a way that I could trouble shoot this through a docker image or something.

**Comment by costastf** [comment]
https://github.com/JohnvandeVrugt/toonapilib4domoticz/blob/5cfe4d2d6270b3933d2373be8a14823c209642ab/plugin.py#L76 references myToon while the global is actually MyToon. Usage of all those globals makes it impossible to reason about the code, having no way to know about the state when it is spread all over the place. 
Of course that should not affect the fact that the value should be set because MyToon is not a variable but an object of which assigning the thermostat state should set it internally. Essentially that global reference with the wrong letter casing should not be there at all, but that does not seem to be the issue with the code.

**Comment by costastf** [comment]
This should be fixed with v3.0.10 of the library that can set temperatures even if the program is set. Thanks for reporting!

**Comment by stephanvdplas** [comment]
I see now that indeed the setpoint change is reflected on the Toon when the program is off. In version 3.0.10 of the ToonApiLib this will be fixed. Great work! 
But is also fixed that setting the program (sleep, away, etc) on the domoticz  selector is not effected on the Toon at this moment? (This was the case in the former ToonThermostat hardware).

**Comment by JohnvandeVrugt** [comment]
No stephan, that requires some work in the plugin.

**Comment by stephanvdplas** [comment]
Clear. It would be great because some of my DZvents Scripts rely on this setting.
The logic is (/should be) that the program of the Thermostat itself is turned off, but the Domoticz selector can switch the home, away, sleep and comfort modes and the Toon reflects this setting without the program be set on. The other way around: The selector should show what state is set on the Toon even when the program is off.

**Comment by JohnvandeVrugt** [comment]
I just committed a new version that supports setting the state of the program.
I cannot remember that the native domoticz toon plugin had a switch to set/unset the program being run.

I'm also not sure that we can set both program state and program 'active' seperately from the toonapilib / toon api.
The Toon app has apart from the program states also an extra switch for the program to run.
We have to investigate that.

**Comment by JohnvandeVrugt** [comment]
I have create a new issue concerning the states. #7

**Comment by stephanvdplas** [comment]
> I'm also not sure that we can set both program state and program 'active' seperately from the toonapilib / toon api.


It is not that you were able to set both program state and program 'active', the thing is that when the program is off on the Toon, you still can use the 4 states (without the automatic evolving to other states of course). These states should be reflected on the Domoticz device, and not as it is doing right now setting the state to 00 (holiday).

**Comment by JohnvandeVrugt** [comment]
Stephan,

please update toonapilib to version 3.0.11. I think I fixed the update issue in the toonapilib.
See https://github.com/costastf/toonapilib/pull/25

**Comment by stephanvdplas** [comment]
3.0.11 is not available. When I upgrade (pip install toonapilib --upgrade) 3.1.0 is installed. I guess this is what you mean :)
I'll try and let you know the outcome.

**Comment by JohnvandeVrugt** [comment]
Yep; moving on! 
I was testing with updating toonapilib through pip and while testing I suddenly ended up with version 3.1.0 as well 😆

**Comment by costastf** [comment]
I just released 3.1.0 that exposes some extra stuff so you guys got that.
The fix is there so you should be good to go.
