### ISSUE TITLE
restore backup

### ISSUE THREAD

**Issue by mariusklop** [JohnvandeVrugt/toonapilib4domoticz#21]
hello i've a question my sd card was dammage. now i have restore a backup but i have now a smal problem can annybody help me
the error is
Error: toon hardware (21) thread seems to have ended unexpectedly
Error: (ToonApiLib) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/toonapilib4domoticz-master/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
Error: (toon) Module Import failed, exception: 'ModuleNotFoundError'
Error: (toon) Module Import failed: ' Name: toonapilib'
Error: (toon) Error Line details not available.

**Comment by darkrain-nl** [comment]
Did you follow the instructions to the letter?

Did you enter this command: sudo pip3 install toonapilib -U 

That is the installation of the library that is used by this plugin.

**Comment by mariusklop** [comment]
thank you, you amazing i nows i forgot somting but i didn't now what. but it works now thank you

**Comment by darkrain-nl** [comment]
No problem, if all is working well now, please close this issue.

Thank you.
