### ISSUE TITLE
Toon new API authentication

### ISSUE THREAD

**Issue by stephanvdplas** [JohnvandeVrugt/toonapilib4domoticz#25]
Toon will use new authentication starting 12/1/2019. See https://developer.toon.eu/authentication for more info.

From December 2019 onwards, Eneco users are required to use the “mijn Eneco” login to access their Toon, use the following call from the application to use the “mijn Eneco” as identity source:

curl -v -k
    https://api.toon.eu/authorize?response_type=code
        &redirect_uri=<redirect_url>
        &client_id=<consumer_key>
        &issuer=identity.toon.eu
        &tenant_id=eneco
From the ToonAPI website's login page, the end user needs to provide his credentials. A redirect will then be performed to the redirect_uri provided before with a code. The application can now use that code and the application key pair to get an access token that looks like this:

curl -k -X POST 
    -H "Content-Type: application/x-www-form-urlencoded"
    -d  "client_id=<consumer_key>
        &client_secret=<consumer_secret>
        &grant_type=authorization_code
        &redirect_uri=<redirect_uri>
        &tenant_id=eneco
        &code=<code>"
    https://api.toon.eu/token 

Again, in this call, when users have logged in via "Mijn Eneco", add the issuer to this request:

curl -k -X POST 
    -H "Content-Type: application/x-www-form-urlencoded"
    -d  "client_id=<consumer_key>
        &client_secret=<consumer_secret>
        &grant_type=authorization_code
        &issuer=identity.toon.eu
        &redirect_uri=<redirect_uri>
        &tenant_id=eneco
        &code=<code>"
    https://api.toon.eu/token

**Comment by stephanvdplas** [comment]
Is the ToonAPIlib4Domoticz compatible with this new authentication method?

**Comment by stephanvdplas** [comment]
A 10-year-valid access token can now be generated via "https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>". I think this key has to be entered somewhere in the ToonApi to connect to the Eneco site.

**Comment by tne7laa** [comment]
I have followed the instruction in my email and managed to get an "Access token" as stated. But I don't have a clue what to do with it. 
Hope someone does understand what they want us to do and explain here for us.

**Comment by rene2716** [comment]
Any news on this?

**Comment by darkrain-nl** [comment]
Version 4 of the library from Costas now has support for this, but that don't work with this plugin for now. Let me check what I can do to make it work.
@JohnvandeVrugt perhaps this is to complicated for my Python skills but I'll try anyway ;)

**Comment by rene2716** [comment]
Keep up the good work guys, hate to see it stop working :)

Op za 30 nov. 2019 15:26 schreef Jan Donker <notifications@github.com>:

**Comment by darkrain-nl** [comment]
I already have it working with the new V4 library, will do a PR soon

**Comment by rene2716** [comment]
Great

Op za 30 nov. 2019 15:55 schreef Jan Donker <notifications@github.com>:

**Comment by darkrain-nl** [comment]
https://github.com/JohnvandeVrugt/toonapilib4domoticz/pull/26 makes this work.

The changes are not really hard to do, just run "sudo pip3 install toonapilib -U" and edit "plugin.py" with what I did in the PR.

**Comment by tne7laa** [comment]
Great work!.
Does anyone also use the [homebridge plugin](https://github.com/jochem725/homebridge-toon)?
I'm using it for controlling Toon via Apple HomeKit and needs also changes I think.

**Comment by rene2716** [comment]
Hi,

Did the adjustments but now its showing below and i do not see device
updates
2019-11-30 17:37:45.534 Error: (toon) 'onStart' failed
'AttributeError':''NoneType' object has no attribute 'smartplugs''.
2019-11-30 17:37:45.534 Error: (toon) ----> Line 112 in
'/home/pi/domoticz/plugins/toonapilib4domoticz/plugin.py', function onStart
2019-11-30 17:37:45.534 Error: (toon) ----> Line 66 in
'/home/pi/domoticz/plugins/toonapilib4domoticz/plugin.py', function on_start
2019-11-30 17:37:45.534 Error: (toon) ----> Line 40 in
'/home/pi/domoticz/plugins/toonapilib4domoticz/devices/device_factory.py',
function create_devices



Op za 30 nov. 2019 om 16:20 schreef Jan Donker <notifications@github.com>:

**Comment by darkrain-nl** [comment]
Then you did not provide an Access Token, sorry I did not tell you to create this first.
Please go to "https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>" where the consumer key is the value you can find on https://developer.toon.eu or more specific https://developer.toon.eu/user/me/apps 

Sorry for not being complete..

**Comment by rene2716** [comment]
Ha, i did but with the wrong consumer key (i have more) and then some
python indent errors to fix (rather strict with last python versions not
used to that :)

all fine now, great job

Op za 30 nov. 2019 om 17:48 schreef Jan Donker <notifications@github.com>:

**Comment by JohnvandeVrugt** [comment]
Thanks Jan, for doing a good job.
I didn't had the time to check out the new API / toonapilib requirements.
