### ISSUE TITLE
Possible Burner_Info addition

### ISSUE THREAD

**Issue by MrPePperNL** [JohnvandeVrugt/toonapilib4domoticz#3]
Hi,

I was using a python script to update my toon in domoticz after a lot of problems with the built in toon hardware.

Checked your plugin and it's becoming awsome.

Just my idea of the burner info (heating,preheat etc):
`
        try:
            Burner = str(MyToon.thermostat_info.burner_info)
            if DebugPrint:
                Domoticz.Log("Burner Info: " + Burner)
            if Burner == '1':
                Domoticz.Log("Heating is on")
                Devices[5].Update(1,"On")
            elif Burner == '0':
                Domoticz.Log("Heating is Off")
                Devices[5].Update(0,"Off")
        except:
            Domoticz.Log("An error occured updating heating device")
`
Not fully complete on all statusses of the burner

PS: Also the log shows wrong text on szSetPoint (Update temperature instead of Update thermostat)

**Comment by JohnvandeVrugt** [comment]
Thanks, I will add the burner states soon.
I also saw the erroneous message. :)

**Comment by MrPePperNL** [comment]
And Hot water  == '2', so we need to update device [6] when burner == '2'.

Too bad the Toon Api is not clearly documented

**Comment by JohnvandeVrugt** [comment]
Added support for burner states yesterday.
