### ISSUE TITLE
how do i connect my consumer key with my toon?

### ISSUE THREAD

**Issue by Bartjee03** [JohnvandeVrugt/toonapilib4domoticz#32]
i have installed the toonapilib and selected the toonapilib in Domoticz in the hardware tab. then created a api at developer.toon.eu and put that public key in the domoticz text field named: ''Access Token:''

Can anyone help me out please?

**Comment by darkrain-nl** [comment]
Did you create an Access Token via "https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>"? If so you should enter that Token in the field and restart Domoticz.
If not then please create a token via the link provided an put the token in the field and restart Domoticz.

Please also make sure Accept new Hardware devices is turned on in Domoticz settings.

**Comment by Bartjee03** [comment]
yea, i put that in the callbackurl with my client id from eneco toon. do i need the public or secret key?

**Comment by darkrain-nl** [comment]
You need to put your Consumer Key in the link I posted earlier, then you receive an Access Token (valid 10 years) and you need to put that into Domoticz.

**Comment by Bartjee03** [comment]
yeah i got it, thx but what do i put in the callbackurl in my toon api app

**Comment by darkrain-nl** [comment]
Whatever you like, the toonapilib doesn't care about the callbackurl, so it can be "localhost" or so...

**Comment by Bartjee03** [comment]
thx, it works now. merry christmas

**Comment by darkrain-nl** [comment]
Merry Christmas and hope you have fun using this plugin.
