### ISSUE TITLE
Toonapi failure

### ISSUE THREAD

**Issue by spacewalker56** [JohnvandeVrugt/toonapilib4domoticz#34]
I used to have rpi 2 (stretch) with a working domoticz installation with toonapilib4domoticz. 
After updating to the latest Domoticz, Toonapi stopped working.
I noticed my hardware form is incomplete just as i describe further on.
On another rp3b+ with cleaninstall raspbian buster with domoticz and the toonapilib4domoticz, everything works except toonapilib. In the hardwaretab i only can provide my access-token and no other values like eneco account and consumer key and consumer secret. I presume Consumer key is the same as access-token.
I would like some help to get it back to work.
![Annotation 2020-03-25 142402](https://user-images.githubusercontent.com/30868984/77541320-ceb6cd80-6ea4-11ea-81fc-adbcb9bcc8ec.png)

**Comment by darkrain-nl** [comment]
> I presume Consumer key is the same as access-token.

No it is not... Please have a look https://github.com/JohnvandeVrugt/toonapilib4domoticz/blob/master/INSTALL_PI.md here and  create an Access Token.

**Comment by spacewalker56** [comment]
Hallo Jan,

Dankjewel. Ik wist dat ik beter moest lezen maar ik had net dat zetje nodig. Het werkt weer.

Groetjes Ruud Tijs

**Comment by darkrain-nl** [comment]
Happy to help!

Please close this issue ;-)

Groetjes!

**Comment by spacewalker56** [comment]
Problem solved. I overlooked requesting the accesstoken via the weblink, After doing that everything worked as before.
