### ISSUE TITLE
domoticz 2020.2

### ISSUE THREAD

**Issue by domoticauser** [JohnvandeVrugt/toonapilib4domoticz#35]
Hello,

Is it possible that the api isn't working anymore with Domoticz 2020.2?

This is the error:

>  2020-04-20 21:16:45.710 Error: (ToonApiLib) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/toonapilib4domoticz/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
> 2020-04-20 21:16:45.710 Error: (ToonAPI) Module Import failed, exception: 'ModuleNotFoundError'
> 2020-04-20 21:16:45.710 Error: (ToonAPI) Module Import failed: ' Name: devices.device_factory'
> 2020-04-20 21:16:45.710 Error: (ToonAPI) Error Line details not available.

**Comment by darkrain-nl** [comment]
Hi,

Working fine on my self build 2020.2 (build 12037).

Did you just install today, or did you do an update?
Let's try to figure out what is wrong...

**Comment by domoticauser** [comment]
I did an update from a beta version (sorry i don't know what build) to stable 2020.2

**Comment by darkrain-nl** [comment]
Ok so before the update it worked?
What OS are you on?

Did you perhaps run "sudo pip3 install toonapilib -U" to have the latest version of the underlying Library?

**Comment by domoticauser** [comment]
Yes, before the update it worked.
  Distro......: Raspbian GNU/Linux 10 (buster)
  Kernel......: Linux 4.19.66-v7+

`sudo pip3 install toonapilib -U`  Yes i did

**Comment by darkrain-nl** [comment]
Are other Python plugins working?

**Comment by domoticauser** [comment]
Yes, the rest is working fine.

**Comment by darkrain-nl** [comment]
Ok, not sure what could be wrong at this point.
Did you also try to download the plugin again and reconfigure the Access Token?

**Comment by domoticauser** [comment]
Just did that, download the plugin again and reconfigure the Access Token

And it works againg!!! Thanks for your support!

**Comment by darkrain-nl** [comment]
That is good news, please close this issue if the issue is resolved ;-)

**Comment by domoticauser** [comment]
Thanks for the good work and support!!
