### ISSUE TITLE
Plugin does not work with stable version v4.9700

### ISSUE THREAD

**Issue by JohnvandeVrugt** [JohnvandeVrugt/toonapilib4domoticz#9]
Related to domoticz issue: https://www.domoticz.com/forum/viewtopic.php?f=65&t=27096

**Comment by pierretje** [comment]
Dit lijkt meer een issue met de stable versie van Domoticz dan met jouw plugin. Denk je dat het met een fix is op te lossen of kan ik toch beter een recentere beta van Domoticz installeren om je plugin te gebruiken?

**Comment by JohnvandeVrugt** [comment]
Don't think I can fix this. So please use the latest beta.
